### ISSUE TITLE
Functional prototype - Dec21

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#1]
### DESC
- approx __mid / start of december__
- "stuff to show" (nothing elaborate): navigation architecture + general setup + no / dummy design + basic workflow(s) providing content + communicate needs (like data protection clause etc.)
- abstract implementation away according to above.
- based on Gatsby + netlify CMS (maybe other stuff to handle other incoming data)

#### Links
- see __Sina's Mockup__ as template!: handled via mockup-plus / needs to be accessed via personal account
- see __Sebi- / Sinas demo__  from summer in zimlab.

### TODOs
- [x] craft according to Sina's mockup / our old gatsby prototype -> start from our demo and adapt to Sina's base layout
- [x] abstract away implementation details for navigation architecture
- [x] craft fully functional prototype

**Comment by Stoff-Sebi** [comment]
implemented / closed old issue
