### ISSUE TITLE
Pair programming session - CMS configuration

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#103]
### DESC
- documentation of pair programming session
- document results + insights

### TODOs
- [ ] check login / roles procedure (need to have write permission to the repo to access the CMS) ---> document
- [ ] check simultaneous data input + simultaneous coding ---> document
- [ ] decide for propper CMS configuration (for individual CMS content models ) ---> document
- [ ] think about general cms data input guidelines --> document
