### ISSUE TITLE
test implement react / gatsby forms -->  use mainly formspree atm / getforms as alternative

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#106]
### DESC
- following the overview of diverse form providers
- https://formspree.io/forms/mqknlgze/integration
- exampe forms on formspree: https://formspree.io/library/

### TODOs
- [x] install formspree package via npm
- [x] craft own component handling event announcements via formspree
- [x] test out a form from formspree somehwre on the hub

**Comment by Stoff-Sebi** [comment]
implemented on http://localhost:8000/portal/events
