### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#11]
### TODOs
- [x] move netlify identity to abstract auth component?
- [x] get rid of old template code
- [x] refactor file components to folder structure
- [x] establish difference between static / shared / etc.
