### ISSUE TITLE
Enhance readme: Write done installation requirements

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#13]
### TODOs
- [x] add installation requirements to the readme
- [x] more detailed dev setup workflow
- [x] add further todos?
