### ISSUE TITLE
Pilot phase consideration

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#133]
### DESC
- CMS should be fully operational in july
- frontend / public interface should be published in pilot phase

### TODOs
- [ ] think about actively communicating pilot phase (maybe alpha / beta phase on the digital hub?)
- [ ] discuss in group
- [ ] decide where to place

**Comment by Stoff-Sebi** [comment]
discussed in group --- not needed
