### ISSUE TITLE
Rework entry page based on requirements from last meeting

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#134]
### DESC
- update base design of entry page according to new requirements
- https://www.figma.com/file/xmDdlfAuqdL5gFd1TF1Z6N/reinheritHOME?node-id=0%3A1 
- figma based
- repeat ReInHerit colors on different locations on page

### TODOs
- [x] implement
- [x] include image attributions
- [x] include images to static folder
- [x] repair base layout on rest of the subpages

**Comment by Stoff-Sebi** [comment]
implemented
