### ISSUE TITLE
Adapt to new navigation architecture

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#136]
### DESC
- new navigation architecture defined in figma prototype

### TODOs
- [x] add CMS link to footer
- [x] create new pages
- [x] adapt links on nav etc.

**Comment by Stoff-Sebi** [comment]
implemented
