### ISSUE TITLE
Use data provided by the netlify cms

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#14]
### DESC
- Sina's enters dummy data ---> use training data!

### TODOs
- [x] craft first intern setup of CMS via neltify (content organisation)
- [x] show on frontend overview
- [x] improve template styling
- [x] show individual pages generated by gatsby iterating over markdown files
- [x] individual pages for news
- [x] enhance training template component!
- [x] test deployment on netlify
- [x] #52
