### ISSUE TITLE
Implement new toolkit requirements

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#143]
### DESC
- according to meeting 23 / 24
- order of components is diffcult to implement! (https://github.com/netlify/netlify-cms/issues/475) --- maybe doing it via list? 

### TODOs
- [x] seperate collection toolkit apps + toolkit components
- [x] adjust needed metadata
- [x] create view generation for toolkit components
- [x] test out intern relative linking

**Comment by Stoff-Sebi** [comment]
implemented
