### ISSUE TITLE
Finish eshop implementation

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#144]
### DESC
- finish current eshop implementation according to new requirements

### TODOs
- [x] add demo / test items
- [x] generate gatsby pages
- [x] implement overview generation
- [x] rewort url pattern
- [x] create own eshop template
- [x] implement view generation

**Comment by Stoff-Sebi** [comment]
implemented
