### ISSUE TITLE
Link from one collection item to another

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#149]
### DESC
- might use template string notation in CMS to reference mutliple fields
- use "____" as seperation mark

### TODOs
- [x] implement for toolkit apps 
- [x] implement for webinars
- [x] implement for toolkit components

**Comment by Stoff-Sebi** [comment]
implemented
