### ISSUE TITLE
Provide base page structure / like data protection clause / 

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#15]
### TODOs
- [x] create footer
- [x] add data protection page via serving from the cms? 
- [x] add imprint via serving from cms
- [x] add further todos
