### ISSUE TITLE
Add social media to digi hub

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#162]
### DESC
- new social media profiles were added since last jour fixe
- add to footer (+somewhere else?)

### TODOs
- [x] add FB : https://www.facebook.com/ReInHerit/
- [x] add TT: https://www.tiktok.com/@reinherit_
- [x] add Twitter: https://mobile.twitter.com/reinherit_
- [x] add linkedIn linkedin.com/company/reinherit-h2020/
- [x] instagram
- [ ] ~~youtube~~ 🔴 not available?
- [x] eu project page? https://www.reinherit.eu/

**Comment by Stoff-Sebi** [comment]
implemented
