### ISSUE TITLE
Search for digital hub

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#163]
### DESC
- implement some kind of search
- maybe fuzzy search
- https://www.gatsbyjs.com/plugins/gatsby-plugin-local-search/?=search
- e.g. https://www.gatsbyjs.com/plugins/@gatsby-contrib/gatsby-plugin-elasticlunr-search/
- idol: https://campus.dariah.eu/
- https://github.com/angeloashmore/react-use-flexsearch
- flexsearch does not support fuzzy search atm!

### TODOs
- [x] install search engine
- [x] configure search indexing
- [x] implement very basic view layer
- [x] add basic input search
- [x] fix wrong type in toolkit components / apps?
- [x] crate template for FAQ / Manual entry
- [x] resolve all collection items to markdown items somewhere! (create template for faq + howto)
- [x] include full textin search?
- [x] fix searching for faq entries
- [x] include type to search result
- [x] check if links to all items work (search links should work to everywhere!)
- [x] configure search behavior (fuzzy etc.)
- [x] display summary of item in search result
- [x] document usage

**Comment by Stoff-Sebi** [comment]
implemented
