### ISSUE TITLE
Remember state where the user came from / like from research at landing page

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#18]
### DESC
- track your selection in the url
- https://www.gatsbyjs.com/blog/2019-01-31-using-react-context-api-with-gatsby/

### TODOs
- [x] mode of global
- [x] use context api ! (see link: https://www.gatsbyjs.com/blog/2019-01-31-using-react-context-api-with-gatsby/)
- [x] craft own Base component that handles fa-setup + context-setup!
- [x] add current mode value somehow to the context
- [x] remove userein hook from baselayout and add useTheme to navbar component
- [x] add change theme / change mode method 
- [x] remove reinherit hook from baselayout
- [x] handleTheme in useTheme must verify that the modeVal is of type ReinheritRestModes
- [x] render nav select according to static data from reinherit
- [x] group key should be available in the theme object -> make somehow available.
- [x] implement
