### ISSUE TITLE
Add card footer(s)  with display of some of the metadata 

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#191]
### DESC
- display some metadata in the card footers
- like in https://rapidapi.com/hub

### TODOs
- [x] Add length as metadata?
- [x] Add license as metadata
- [x] add to tools
- [x] news
- [ ] webinars
- [x] eshop
- [x] implement
