### ISSUE TITLE
Add musem-collection as netlify cms collection

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#195]
### DESC
- images are stored via google forms and need to be referenced somehow? (best would be to store image files with same page-ids)
- need own CMS template to provide necessary data

### TODOs
- [ ] implement CMS template
- [ ] think about external image handling workflow
- [ ] add coordinates as field
- [ ] add museum name
- [ ] author
- [ ] date = period as string
- [ ] place
- [ ] title
- [ ] team of exhibition
- [ ] embedment of 3d models

**Comment by Stoff-Sebi** [comment]
issue needs to be recreated because of result from last meeting
