### ISSUE TITLE
Image problem: Checkout git LFS systems / uploadcoare integration

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#198]
### DESC
- github LFS and netlify cms cannot be integrated atm
- maybe write some kind of script to add things to github LFS? 
- store large media outside of github workflow
- https://www.netlifycms.org/docs/uploadcare/
- gatsby: process images into public folder / static web page via sharp + image-remark

### Git LFS
- https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage
- https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage

### TODOs
- [x] test out netlify CMS and uploadcare integration
- [x] local images are not being displayed currently on the hub
- [x] test out manual git github LFS integration
- [x] try to introduce develop branch --> CMS commits only against main
