### ISSUE TITLE
Rework digital exhibition / collection page(s)

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#202]
### DESC
- new results from meeting 
- documented in private pdf sent by partners

### TODOs
- [x] add more todos according to sent requirements
- [x] create new base page
- [x] add to navigation
- [x] take over base design
- [x] take over static content
- [x] create netlifyCMS collection according to defined needs
- [x] setup graphql rendered overview as react component 
- [x] render own page per collection-object

**Comment by Stoff-Sebi** [comment]
implemented
