### ISSUE TITLE
Update reinherit logo

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#216]
### DESC
- update logo with one without text

### Tasks
- [x] add logo sent from sina
- [x] display on nav
- [x] think about if necessary somewhere else

**Comment by Stoff-Sebi** [comment]
implemented
