### ISSUE TITLE
Update filtering / taxonomy of museum collection

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#250]
### DESC
-  add to cms 
- retrieve tags dynamically out of returned result data

### TASKs
- [x]  retrieve tags dynamically out of returned result data
- [x] apply to tool components
- [ ] wait for finished taxonomy
