### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#251]
### DESC
- someone needs to be able to code / 
- structure of github (deployment / development / production )
- like code structure
- CMS / software lifecycles

### TASKs
- [x] update readme: refactor  / update outdated section
- [x] update readme:  add sections about code structure
- [x] add tasks
- [x] create a google doc --- about internal things
- [x] document how to access netlify / uploadcare / etc.

**Comment by Stoff-Sebi** [comment]
implemented
