### ISSUE TITLE
Redeployment based on git push events

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#252]
### DESC
- search for easy implementations
- write down some stuff
- test: only trigger redeploy on news section
- deployment script --- document how to do it --- elaborate
- https://github.com/marketplace/actions/gatsby-publish
- https://www.andrewvillazon.com/automatically-deploying-with-github-actions/

### RESULTS
- automatic remote deployment might be unreliable in the long run (complex to setup - oauth2 + external dependencies)
- deployment script can be used locally -> workflow is more robust

### TASKs
- [x] elaborate deployment script
- [x] document deployment script
- [x] build in fail-safe mechanism
- [x] check pull request based workflow?

**Comment by Stoff-Sebi** [comment]
implemented
