### ISSUE TITLE
Early Prototyping: Try out / test gatsby with netlify cms

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#3]
### DESC
- enhance early prototype with netlify cms functionalities

### TODOs
- [ ] collect links related professional setup of gatsby + netlify cms
- [ ] think about iterating dev 
- [ ] think about: backup strategy
- [ ] read through best practices / hints / tutorials
- [ ] test out deployable early prototype as soon as possible
