### ISSUE TITLE
Check out: Online image manipulation like in rijks-studio 

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#34]
### DESC
- https://www.rijksmuseum.nl/en/rijksstudio
- would be cool to somehow integrate?
- toastUi editor seems to be very unstable and unreliable!

### TODOs
- [x] add component https://www.npmjs.com/package/@toast-ui/react-image-editor
- [x] play around a bit
- [x] add test playground
- [x] react component fails at build
- [x] test out via cdn - https://github.com/nhn/tui.image-editor/tree/master/apps/image-editor
- [x] test out via requiring as commonjs module
- [x] download cdn included css files
- [x] include css files from static folder
- [x] test out handle image change via state? --> give url as prop
- [x] add custom css: hide toast UI logo etc.?
- [x] craft own component 'EngageImage' -> allows to call image inside editor
- [x] decide to show image via popover?
- [x] create pre-release + deploy
- [x] #49
