### ISSUE TITLE
Jour Fixe 09.11.2021 - Keep two versions of page

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#35]
### DESC
- new todos according to jour fixe on 09.11.2021

### TODOs
- [x] #38
- [x] #37
- [x] #36
- [x] fill in entry page cards (data provided by chiara --- via mail) --> postponed wait for data
- [x] write dummy lines on training page // embed a video
- [x] take descirption from sina's tables for additional content

---------------------------------

### TODOs (2)
- [x] sitemap / information-architecture - create somekind as basis for future discussions
- [x] CORS Errors -> test out to load data from google sheet? (how to do it)
