### ISSUE TITLE
two cols for target audience instead of 4

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#37]
### TODOs
- [x] reduce types to professionals + visitors
- [x] adapt static data
- [x] resize cols on entrance
