### ISSUE TITLE
Handle image upload on the Hub

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#45]
### DESC
- maybe pinterest + providing links

### TODOs
- [x] fix fire not defined bug
- [x] add more menu points to manipulation?
- [x] check if editor is startable e.g. on image click?
- [x] hide Logo-label from toast-ui
