### ISSUE TITLE
Gatsby with netlify CMS

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#5]
### DESC
- God tutorial: https://www.freecodecamp.org/news/how-to-build-a-blog-with-gatsby-and-netlify-cms/
-  netlify documentation: https://www.netlifycms.org/docs/add-to-your-site/
- run local dev server: https://www.netlifycms.org/docs/beta-features/
-----------------------
- example netlify-cms setup: https://cms-demo.netlify.com/#/collections/posts
- example netlify-cmks code: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml 

--------------------------
### TODOs / setting up via finished plugin
- [x] basic installation -> 🟥 fails due to cross deps problem
- [x] resolve netlify cms plugin bug -> downgrade to 5.0.3? see https://github.com/gatsbyjs/gatsby/issues/31102 -> 🟥 fails du e to new version of gatsby?

### TODOs / setting up by hand
- [x] setting up local backend on own server (see link in DESC in issue)
- [x] set up CMS connection by hand without plugin
- [x] test out local dev -> adding of images and blog post
- [x] test out additinal content models -> like for exhibition + dynamic pages? (could load via markdown plugin then)
- [x] creating own component that handles setup of netlify CMS via cdn and script tag
- [x] test out deployment on netlify
- [x] create more issues based on additional requirements
