### ISSUE TITLE
Embed videos in the CMS

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#50]
### DESC
- https://www.iliascreates.com/blog/post/embeding-youtube-videos-markdown-gatsby-netlifycms/
- https://www.youtube.com/watch?v=AcvF95VcXHY&ab_channel=DARIAHEthics%26Legality
- embed a dummy playlist!

### TODOs
- [x] allow addition of youtube videos to the CMS
- [x] embed youtube video gotten from markdown
- [x] implement adding video links to the CMS
- [x] implement visualisation of videos on the page
