### ISSUE TITLE
Databasket - able to collect stuff on page and display in own custom collection

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#53]
### DESC
- databasket
-  combine with drilldown app?
### TODOs
- [x] need to access array via state array -> otherwise state updates won't appear! --> state need to be handled outside!
- [x] create own Databasket component
- [x] added generic typing for objects-types available in collection
- [x] improve typing (type of saved objects?)
- [x] show different faicons per saved type
- [x] display more information on databasker overview?
- [x] add functional overview over collected information on left side (counts etc.)
- [x] finish share / import functionality

**Comment by Stoff-Sebi** [comment]
wholedatabasket needs to be refactored according to new requirements
