### ISSUE TITLE
Redo styling 

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#58]
### DESC
- mixture between https://reinherit.eu/ and https://campus.dariah.eu/

### TODOs
- [x] change fonts?
- [x] allow to add training to personal collection!
- [x] add more dummy data to training
- [x] make card grid own component
- [x] make card own component
- [x] create somewhat card grid combined with list overview
- [x] reuse for news page
- [x] reuse on training overview
- [x] add dummy news data!
- [x] card grid for my collection
- [x] internal area with FAQ / Report a bug / Documentation etc. ?
- [x] add some kind of alert library that better visualizes interaction
