### ISSUE TITLE
Basic navigation architecture / design considerations based on Sina's mock

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#6]
### DESC
- https://app.mockplus.com/team/vcnjcnamfx
- related issue: https://github.com/ReInHerit/digital-hub/issues/19

### TODOs
- [x] serve news via CMS? / markdown
- [x] how about loading the news dynamically? from one file etc. --> tested out via the about page
- [x] create pull request / pre-release for new version
- [x] gatsby redirects -> not working in deploment 🔴 (need a plugin?)
- [x] allow selection of tags on a content model: like on news posts
- [x] display news conditionally based on selection
- [x] add training collection page / according to content served from netlify CMS
