### ISSUE TITLE
Add own SideMainLayout component and reuse

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#62]
### DESC
- add own component for sideMain

### TODOs
- [x] create component
- [x] reuse in news section
- [x] reuse in personal collection section
- [x] reuse at training overview
