### ISSUE TITLE
Sharing content of drilldown app

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#63]
### DESC
- https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/
- Need to care for stable and globally unique ids for myself? https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#createNodeId
- Need to generate stable URLs somehow: think about: maybe document in a json file which content type has what id assigned? (could also allow a somewhat stable mechanism to define via slug on indiv markdown pages)

### TODOs
- [x] save all slugs to pageIdArray saved inside a json
- [x] gatsby-node.js:  correct workflow to slug workflow from here: https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/ ---> this is not really necessary.
- [x] think-about: why needing encoded type of markdown?
- [ ] import when databasket is emtpy doesn't work!
- [ ] craft own component handling sharing + importing of storage data via url
- [x] write imported data to local storage --> create method inside hook!
- [x] think about: what is stored in the localStorage? (maybe only markdownId is enough?)
- [x] move complete layouting to databasket component
- [x] need to also import exceprt now for the import component!
- [ ] import when databasket is empty doesn't work!
- [ ] create share link  --> copy to clipboard 
- [ ] refactor code

**Comment by Stoff-Sebi** [comment]
use case is outdated
