### ISSUE TITLE
Technical Documentation on Digi-Hub

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#64]
### DESC
- need some kind of documentation / technical + business logic (Dimitris)
- take a look at: https://campus.dariah.eu/docs/about

### TODOs
- [x] add own documentation page / nav element / project about? (documentation as part of project about?)
- [x] create UML Use case diagram
- [x] add use-case-diagram to the page
- [x] C4 architecture diagram
- [x] craft c4 - layer1 system context diagram
- [x] craft c4 - layer2 container diagram
- [x] craft c4 - layer3 component diagram --> Client Side Apps component
- [x] craft c4 - layer3 component diagram --> Netlify CMS component
- [x] craft c4 - layer3 component diagram --> Web App: Generated Site Component
- [x] redo design according to tutorial page
- [x] additional documentation
