### ISSUE TITLE
E-Shop according to meeting 03.12

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#65]
### DESC
- want to place digital objects on the page
- https://docs.google.com/document/d/1_U8cnqMLP2aoAaJX1cJaqFz-nMs2xSnnylq_W-umGGU/edit
- databasket as shared usecase for all reinherit partners
- documentation handled in issue: 
- shared use cases / business logic ---> documentation + databasket ---> present shared use-case(s) across the Hub

### TODOs
- [x] add to cms demo of digital objects --> postponed after meeting on 10.12
- [x] add image gallery for next meeting session to nav
- [x] redeploy to netlify for showcase etc.
- [x] create new release to proof existing functionality
