### ISSUE TITLE
Toolkit new navigation architecture 

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#67]
### DESC
- update prototype according to results from meeting with marco
- think about common concepts / attributes / relations
- think about: training is subtype from indiv toolkit markdown pages or individual markdowns? (check referencing system of NETLIFY CMS)

### TODOs
- [x] redo nav
- [x] redo overview page
- [x] redeploy + tell sina AND chiara
- [x] fix styling on small laptops (alignment rows / cols)
- [x] allow singular toolkit pages?
- [x] remove faceted filtering --> only apply stuff to on tag level! (combine with search of tags?)
- [x] create ToolkitFeed component to display all available toolkits?
