### ISSUE TITLE
Internal Area / Portal page

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#69]
### DESC
- should be somewhat like the overview of UGO
- displays different use-cases + links to different pages
- 

### TODOs
- [x] move stuff from old admin area to portal
- [x] refactor old nav to new
- [x] check sina's overview
- [x] take existing portal page: craft like portal / UGO overview
- [x] card should have some hover styles applied to them
- [x] add: report a bug card
- [x] in the footer of each card you should have a direct link available (if necessary)
- [x] craft pages "behind" use case oriented navigation cards --> in case of the portal page!
