### ISSUE TITLE
Loading data from static data paths via js fetch and not static rendering

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#7]
### DESC
- could also load content on the fly instead of static rendering
- static rendering is most profitable for SEO but often not really necessary -> makes no difference for the user
- could register content to static and then fetch it from there?
- could also write own deployment script in production to move content to public? (maybe thats even more elegant?)

### TODOs`
- [x] test out on the fly fetching via sites json first.
- [x] rendering the markdown from the page jsons
- [x] test out news section? -> render aggregation via gatsby markdown plugin and graphql api
- [x] markdown to html setup via the standard gatsby plugins (remark etc.?)
- [x] what about a news section?
