### ISSUE TITLE
Quick Access Bar 

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#71]
### DESC 
- some kind of bar with icons to allow quick access to base functionality like chat / forum etc.
- maybe as sidebar to the right would be best

### TODOs
- [x] first impl
- [x] hide on mobile via bootstrap / react-bootstrap
- [x] add dummy search icon?
- [x] strengthen with some kind of hover effect
