### ISSUE TITLE
Redo markdown template page

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#73]
### DESC
- general layout + prop drilling design is a bit outdated

### TODOs
- [x] sidebar should display all necessary meta-information
- [x] display symbols according to type of markdown
- [x] reuse existing side/main layout?
- [x] fix / implement
