### ISSUE TITLE
Meeting 18.01.

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#76]
### TODOs
- [x] sorting according to target group
- [x] use hash tags
- [x] toolkit -> refactor metadata (add link to tool)
- [x] #79
- [x] databasket -> move type of item to the left
- [x] #80
- [x] tags being described somehow / somewhere
- [x] draw.io of system components
- [x] show case
- [x] forms
- [x] embed gitter

**Comment by Stoff-Sebi** [comment]
implemented everything - issue is somewhat legacy
