### ISSUE TITLE
Embed Chat = Gitter on page

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#77]
### DESC
- https://sidecar.gitter.im/
- could do also private chat rooms based on repos in the project - or via invite

### TODOs
- [x] test out embedding gitter on the page
- [x] craft own component
- [x] make ReinHerit a public organisation on github -> changed visibility to public
- [x] update quick access links
