### ISSUE TITLE
Meeting 25.01.2022

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#78]
### DESC - Requirements engineering
- digital exhibitions / documentation
- travelling exhibition as basic content 
- exhibition -> 
- 360 Type of thing / 3 sub pages for Digital Exhibitons
- https://360.grazmuseum.at/en/epochen/1600-1809/#urban-development 
- Travelling exhibitions: Documentation (page) / Like a GAMS page?  / 
- open database of traveling in europe? / people should be able to contribute (people can upload their traveling exhibitons) --- people uploading it -> then moderation. (e.g. Pandas in Europe? / can add like - download material ) --- like a popup exhibitions // add their own objects? // spatial information is important --- 

### Requirements  Performances
- two sub pages for the two performances
- different requirements
- performance 1 --> just documentation / metadata (where the performance is less important)
- maybe like toolkit / searchable material? / 
- abstract material (media-type / author / user? / ) --- need to know better what thy want to have
- performance2 --> embedding / need to tell us what kind of tools they want to use (quick tools for stuff)

### TODOs
- [x] Recraft Navigation -> Exhibition -> (Travelling / Digital Exhibition)
- [x] whitepage for Digital Exhibition Sub page
- [x] whitepage for travelling exhibition 
- [x] performance 1 -> emtpy page
- [x] performace 2 -> emtpy page
- [x] forms part / data provided by the public
- [x] experiment with forms / multiple type of forms for people to upload different data models / gatsby-forms (we need moderation) --- does the form work or not? 
- [x] (not an urgency) static texts on the web page

**Comment by Stoff-Sebi** [comment]
covered in #90 and implemented
