### ISSUE TITLE
Add initial netlify cms config template

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#8]
### DESC
- moved from #5 
- craft a more elaborate config with commentary etc.

### TODOs
- [x] talk to Sina / division of work / setting up the cms via config.yml
- [x] add map / generating geojson?
- [x] add slogan content for entry page?
- [x] add FAQ area?
- [x] etc.
- [x] implement
