### ISSUE TITLE
Switch authentication workflow to github

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#81]
### DESC
- switch authentication workflow to github
- according to: https://www.netlifycms.org/docs/github-backend/

### TODOs
- [x] create own branch to save netlify setup --> not necessary added comments + documented in commit and issue
- [x] follow required ouath steps for config!
- [x] redeploy and test-out!
- [x] implement
