### ISSUE TITLE
Test out deployment on github pages

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#83]
### DESC
- alternative deployment location / failsafe
- ist the website deployable on gh-pages?
- https://github.com/digitalinteraction/vercel-netlify-cms-github#readme
- https://github.com/digitalinteraction/vercel-netlify-cms-github/issues/6
- https://preview-auth-doc--netlify-cms-www.netlify.app/docs/authentication-backends/
- https://sujaykundu.com/blog/how-to-setup-netlify-cms-with-github-pages-hosted-jekyll-blog/
- might be better to deploy to organisations root repo!

### TODOs
- [x] create own gh-pages branch
- [x] need to publish repository first?
- [x] push deployment code to gh-pages ---> deploy to reinherit.github.io! this is easier (!)
- [x] delete gh-pages branch
- [x] tets out deployment (are all functionalities working as expected?)

**Comment by Stoff-Sebi** [comment]
works as expected (except some minor bugs)
