### ISSUE TITLE
Meeting 04.02.2021

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#86]
### DESC
- meeting protocol
- implication of hosting / pricing / consider deployment
- https://docs.github.com/en/pages/getting-started-with-github-pages/unpublishing-a-github-pages-site#unpublishing-a-user-or-organization-site

### Use cases
- able to write but not to delete
- three levels: owners (full power) - contributers (netlify CMS / project partners) - members (join chat etc. / see something / cannot modify website + not delete stuff from the chat)

### Workshop
- prepare / introduc google jambard
- 'miro' tool also an idea
- each one of us is managing one virtual board / collecting requirements / feeedback during the workshop

### TODOs
- [x] disable github deployment again --> renamed it so it is unpublished!
- [x] #92
- [x] relabel to e-shop (designs is not the right use-case)
- [x] climate change (consider applyign a dark mode) --- only if easy to implement

**Comment by Stoff-Sebi** [comment]
implemented / created own issues
