### ISSUE TITLE
Test deployment of netlify CMS

### ISSUE THREAD

**Issue by Schiller-Stoff** [ReInHerit/digital-hub#9]
### DESC
- test out complete deployment of netlify CMS + auth etc.
- Tutorial: https://www.freecodecamp.org/news/how-to-build-a-blog-with-gatsby-and-netlify-cms/
- ( there is an own identity tab available on the netlify site settings) a bit hard to find but here --> https://app.netlify.com/sites/distracted-torvalds-d96327/identity

------------------
- deployment-link: https://61646fc26779b9000701068d--distracted-torvalds-d96327.netlify.app/

### TODOs
- [x] deploy plain page on netlify
- [x] deploy with authentication
- [x] show that adding content is now possible
- [x] create own deployment branch 
- [x] think about release workflow: adjust netlify to deploy from the dedicated deployment branch
- [x] test out if working -> deployment from dedicated branch
- [x] implement
