### ISSUE TITLE
Play around / test out story telling possibilites

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#91]
### DESC
- judge development requirements for implementing some kind of scrollitelling
- via react scrollama
- react leaflet etc.

### TODOs
- [x] test out react scrollama
- [x] test out react leaflet
- [x] talk in group about non functional requirements

**Comment by Stoff-Sebi** [comment]
implemented
