### ISSUE TITLE
specificely assign different roles / rights for CMS (as mentioned under Use Cases section)

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#92]
### DESC
- apply settings to Sina
- test out different settings / access roles with different github accounts
- e.g. how can we access the chat? / how can we push to the CMS / what rights / roles are needed?
- check out team functionality with different access levels

### TODOs
- [x] test out access lvls to gitter
- [x] test out access lvls to the CMS
- [x] how is read / write access behaving in the CMS? how can I hinder the login?
- [x] add admin to the documentation
- [x] move to auhtorization page in the documentation / place link at cms page

**Comment by Stoff-Sebi** [comment]
implemented
