### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#93]
### DESC
- add more doc e.g. to deployment / rights / access lvls etc.
- documentation - report for july + guidelines // may

### TODOs
- [ ] doc deployment on gh-pages (how to enable / disable reinherit.github.io)
- [ ] doc access lvls to chat / CMS
- [ ] document how to develop the digital hub / 
- [ ] document general github workflow / structure of the hub (github organisation / individual github accounts)

**Comment by Stoff-Sebi** [comment]
implemented
