### ISSUE TITLE
Test-playground for Reinherit

### ISSUE THREAD

**Issue by Stoff-Sebi** [ReInHerit/digital-hub#94]
### DESC
- create a branch / so that partners may test out functionality 
- maybe on netlify / 
- as soon as possible --> deactivate features not necessary

### TODOs
- [x] temp deactivate the gitter chat
- [x] fix linking bug in the navbar
- [x] deploy to netflify branch
- [x] communicate new release
- [x] reenable stuff for dev
